# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8d92a96e8295bd8fe60121a6df1ce97f4a74becc80e773218899668149b66fea44c026170eb92a5fd74e027a7f8c037094eaad5ef8fe09e35298ddd46213df7

test:
  secret_key_base: c6983e5431636c32bcc59cfc9a848af1080c63cb1b8e799b206e37f36bbc179cf41cc15612a75ecff63589c6be7447d7d78694685324f7de02060061c7d0833e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
